[build]
  command = "npm ci --prefer-offline --no-audit --no-fund && npm run build"
  publish = "dist"

[[redirects]]
  from = "/design-research/*"
  to = "/design-research/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_CACHE = "/opt/build/cache/npm"
  CI = "true"